import {
  ContentDashboardComponent,
  ContentTreeComponent,
  AppContentSidebarComponent,
  TemplateSelectorComponent,
  TemplateSelectorDialogComponent,
  InitialContentCreatorComponent,
  FieldsRendererComponent,
  SingleLineTextRendererComponent,
  ContentDetailComponent,
  ContentResolver,
  RichTextRendererComponent,
  MultilineTextRendererComponent,
  ContentVersionResolver,
  ContentRenameDialogComponent,
  EntityAccessDialogComponent,
  EntityAccessEditorComponent,
} from 'app/components';
export const ContentComponents = [
  ContentDashboardComponent,
  ContentTreeComponent,
  AppContentSidebarComponent,
  TemplateSelectorComponent,
  TemplateSelectorDialogComponent,
  InitialContentCreatorComponent,
  FieldsRendererComponent,
  SingleLineTextRendererComponent,
  ContentDetailComponent,
  RichTextRendererComponent,
  MultilineTextRendererComponent,
  ContentRenameDialogComponent,
  EntityAccessDialogComponent,
  EntityAccessEditorComponent,
];

export const ContentResolvers = [ContentResolver, ContentVersionResolver];
