import {
  LoginService,
  ApiService,
  AuthenticationService,
  AuthGuard,
  ClientState,
  UserService,
  RoleService,
  LayoutService,
  FileUploadService,
  OrganizationService,
  ColorService,
  ModuleService,
  OrganizationRoleService,
  FeatureService,
  LayoutManagementService,
  WebsiteManagementService,
  TemplateManagementService,
  IconService,
  FileService,
  ResponseCachingService
} from '@services/index';

export const SharedServices = [
  LoginService,
  ApiService,
  AuthenticationService,
  AuthGuard,
  ClientState,
  UserService,
  RoleService,
  LayoutService,
  FileUploadService,
  OrganizationService,
  ColorService,
  ModuleService,
  OrganizationRoleService,
  FeatureService,
  LayoutManagementService,
  WebsiteManagementService,
  TemplateManagementService,
  IconService,
  FileService,
  ResponseCachingService
];
