import {
  LoginComponent,
  DashboardComponent,
  LoadingStateComponent,
  ManageUsersComponent,
  PageHeadingComponent,
  AddUserComponent,
  UserProfileComponent,
  ChangePasswordDialogComponent,
  UserFilterComponent,
  ChangeAvatarDialogComponent,
  ManageOrganizationComponent,
  AddOrganizationComponent,
  OrganizationFormComponent,
  OrganizationFilterComponent,
  OrganizationAssignBoardComponent,
  ManageOrganizationRolesComponent,
  TwoSideSelectComponent,
  AddOrganizationRoleComponent,
} from 'app/components';
import {
  ApplicationLayoutComponent,
  AppHeaderComponent,
  AppHeaderLogoComponent,
  AppHeaderInfoComponent,
  AppHeaderQuickLinkComponent,
  AppSidebarComponent,
  AppNavigationComponent,
} from 'app/components/_layout';
export const SharedComponents = [
  LoginComponent,
  DashboardComponent,
  LoadingStateComponent,
  ManageUsersComponent,
  PageHeadingComponent,
  AddUserComponent,
  ApplicationLayoutComponent,
  AppHeaderComponent,
  AppHeaderLogoComponent,
  AppHeaderInfoComponent,
  AppHeaderQuickLinkComponent,
  AppSidebarComponent,
  AppNavigationComponent,
  UserProfileComponent,
  ChangePasswordDialogComponent,
  UserFilterComponent,
  ChangeAvatarDialogComponent,
  ManageOrganizationComponent,
  AddOrganizationComponent,
  OrganizationFormComponent,
  OrganizationFilterComponent,
  OrganizationAssignBoardComponent,
  TwoSideSelectComponent,
  AddOrganizationRoleComponent,
  ManageOrganizationRolesComponent,
];
import {
  UserResolver,
  OrganizationResolver,
  OrganizationRoleResolver,
} from 'app/components';
export const SharedResolvers = [
  UserResolver,
  OrganizationResolver,
  OrganizationRoleResolver,
];
